config/routes.rb
Derelicte::Application.routes.draw do
  
  match ':version/users', :to => 'user#new', :via => ["post"] # CREATE: Register new user with access_token
  
  match ':version/search', :to => 'mealtime#search', :via => ["get"]
  match ':version/business/:yid', :to => 'mealtime#business', :via => ["get"]
  
  match ':version/mealtime', :to => 'mealtime#dump', :via => ["post"] # MealTime app client dumps go here

  match '/privacy',  :to => 'pages#privacy'
  match '/terms', :to => 'pages#terms'
  match '/beta', :to => 'pages#beta'
  
  root :to => 'pages#home'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def beta
    @foos = params[:email]
    puts @foos
    
    respond_to do |format|
        format.html { redirect_to(home_url, :notice => "Email saved.") }
        format.js
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/beta.js.erb
$('.emailform').html("Thank you! <%= escape_javascript(@foos)%> added!");

app/views/home/index.html.erb
	<div id="page">

	  <div class="header">
		<img class="logo" src="/assets/7ml-logo.png">

	  </div><!-- /end .header -->
	
	  <div class="blog">
		
		<div class="left">
		  <div class="recentl">	
		  </div><!-- /end .recentl -->
	    </div><!-- /end .left -->
	
		<div class="main">
			<div class="messageunit">
			  <div class="lense">	
			    <img class="title" src="/assets/lense-logo.png">
			  </div>
			  <div class="emailform">
				<%= form_tag(beta_url, :remote => true, :method => "post") do %>
				  <%= label_tag(:email, "Enter your email to enter the beta:") %>
				  <%= text_field_tag "email", nil, :type => "email", :class => "email" %>
				  <%= submit_tag "Submit", :class => "submit"%>
				<% end %>
			  </div>
			  <div class="appstorebadge">
				<img class="badge" src="/assets/app_store_badge.png">
			  </div>
			</div><!-- /end .messageunit -->	
		</div><!-- /end .main -->
		
		<div class="right">
			<div class="recentr">
			  <div class="iphonebox">
				<img class="iphone" src="/assets/iphone.png">
			  </div>	
			</div><!-- /end .recentr -->
	    </div><!-- /end .right -->
	
	  </div><!-- /end .blog -->
	
		<div id="footer">
		  <div class="footmain">
		  </div><!-- /end .footmain -->
		</div><!-- /end #footer -->
		
	</div><!-- /end #page -->